/**
 * SOURCED BASELINE TEMPLATES — NOT GENERATED BY LLM
 *
 * Source Documentation & Statutory References:
 * 1. Model Tenancy Act (MTA) 2021, Ministry of Housing and Urban Affairs, Government of India.
 * 2. Fairwork India Criteria (Fair Contracts, Fair Due Process, Fair Governance).
 * 3. Section 27, Indian Contract Act 1872 (Agreements in Restraint of Trade Void).
 */

export interface BaselineClause {
  readonly id: string;
  readonly type: string;
  readonly title: string;
  readonly standardText: string;
  readonly legalNormRationale: string;
}

export interface BaselineTemplate {
  readonly id: "residential_tenancy" | "gig_worker_agreement" | "employment_offer";
  readonly title: string;
  readonly category: string;
  readonly sourcedReference: string;
  readonly clauses: readonly BaselineClause[];
}

export const BASELINE_TEMPLATES: Record<string, BaselineTemplate> = {
  residential_tenancy: {
    id: "residential_tenancy",
    title: "Model Residential Tenancy Reference Standard",
    category: "Tenancy & Housing",
    sourcedReference: "Ministry of Housing & Urban Affairs — Model Tenancy Act (2021)",
    clauses: [
      {
        id: "base_tenancy_deposit",
        type: "security_deposit",
        title: "Security Deposit Ceiling & Refund",
        standardText:
          "The security deposit shall not exceed two months' rent for residential premises. The deposit shall be refunded in full within thirty (30) days of the tenant vacating the premises, subject only to actual deductions for documented unpaid utilities or physical damages beyond normal wear and tear.",
        legalNormRationale:
          "Section 11, Model Tenancy Act: Deposits are strictly capped at 2 months' rent for residential properties and must be returned within 30 days.",
      },
      {
        id: "base_tenancy_notice",
        type: "notice_period",
        title: "Reciprocal Notice Period",
        standardText:
          "Either party may terminate the tenancy by providing sixty (60) days advance written notice to the other party. The notice period applies symmetrically to both Lessor and Lessee.",
        legalNormRationale:
          "Customary fair practice requires equal reciprocal notice for eviction and vacating to prevent abrupt displacement.",
      },
      {
        id: "base_tenancy_entry",
        type: "landlord_entry",
        title: "Notice for Landlord Entry",
        standardText:
          "The Landlord or their authorized agent shall give at least twenty-four (24) hours advance notice in writing or via electronic message before entering the premises for inspection or maintenance, between 9:00 AM and 6:00 PM.",
        legalNormRationale:
          "Section 15, Model Tenancy Act: Protects tenant privacy with mandatory 24-hour advance notice during daytime hours.",
      },
      {
        id: "base_tenancy_maintenance",
        type: "maintenance_repairs",
        title: "Allocation of Maintenance Obligations",
        standardText:
          "Major structural repairs, whitewashing, plumbing supply lines, and electrical conduits remain the responsibility of the Landlord. Routine maintenance and internal repairs arising from daily use are the responsibility of the Tenant.",
        legalNormRationale:
          "Schedule II, Model Tenancy Act explicitly divides structural vs routine maintenance duties.",
      },
    ],
  },
  gig_worker_agreement: {
    id: "gig_worker_agreement",
    title: "Fair Platform Partner Reference Standard",
    category: "Gig Work & Logistics",
    sourcedReference: "Fairwork Principles & Social Security Code Norms (2020)",
    clauses: [
      {
        id: "base_gig_deactivation",
        type: "account_deactivation",
        title: "Fair Notice Before Account Deactivation",
        standardText:
          "Company shall not deactivate, suspend, or block Partner's account without providing at least seven (7) days advance written notification specifying the grounds, along with a meaningful human appeal mechanism to contest the action.",
        legalNormRationale:
          "Fairwork Principle 2 (Fair Contracts & Fair Due Process): Unilateral deactivation without notice or appeal deprives workers of livelihoods.",
      },
      {
        id: "base_gig_indemnity",
        type: "indemnity_liability",
        title: "Mutual & Capped Indemnification",
        standardText:
          "Each party's indemnification obligations shall be strictly limited to direct damages caused by gross negligence or willful misconduct, capped at the total payouts earned by Partner in the preceding thirty (30) days. Partner shall not indemnify Company for third-party traffic or transit claims.",
        legalNormRationale:
          "Uncapped partner indemnification is unconscionable and legally vulnerable under Section 23 of Indian Contract Act.",
      },
      {
        id: "base_gig_deductions",
        type: "pay_deductions",
        title: "Evidentiary Proof for Pay Deductions",
        standardText:
          "No penalty, deduction, or withholding shall be applied to Partner's earnings without verifiable photographic or telemetric proof presented to the Partner, and opportunity for immediate review.",
        legalNormRationale:
          "Protects against automated or arbitrary deductions without due process.",
      },
    ],
  },
  employment_offer: {
    id: "employment_offer",
    title: "Fair White-Collar Employment Reference Standard",
    category: "Employment & Labor",
    sourcedReference: "Indian Contract Act (Section 27) & Model Employment Practices",
    clauses: [
      {
        id: "base_emp_notice",
        type: "termination_notice",
        title: "Balanced Probation & Notice Period",
        standardText:
          "During the probationary period, either party may terminate employment with thirty (30) days notice or payment in lieu thereof. Post-confirmation, the notice period shall be sixty (60) days, applicable mutually to both Employer and Employee.",
        legalNormRationale:
          "Asymmetric notice periods (e.g. 90 days for employee, 15 days for employer) create unfair contractual bondage.",
      },
      {
        id: "base_emp_noncompete",
        type: "post_termination_noncompete",
        title: "Post-Employment Restraint Limits",
        standardText:
          "Employee agrees not to solicit existing company clients or colleagues for twelve (12) months. Any restriction preventing Employee from exercising a lawful profession or seeking employment after termination is void.",
        legalNormRationale:
          "Section 27, Indian Contract Act: Any agreement in restraint of trade or lawful profession post-termination is void as a matter of public policy.",
      },
      {
        id: "base_emp_ip",
        type: "ip_assignment",
        title: "Fair Scope of Intellectual Property Assignment",
        standardText:
          "Employee assigns to Company rights in inventions and works created directly in the performance of job duties using Company resources. Inventions created entirely on Employee's personal time without using Company trade secrets or tools remain Employee's sole property.",
        legalNormRationale:
          "Overreaching 24/7 IP capture of personal hobby projects is overbroad and disproportionate.",
      },
    ],
  },
};
