"use client";

import dynamic from "next/dynamic";
import { useState, useMemo } from "react";
import { type ParsedDocument } from "@/features/ingestion/types";
import { type Clause, type DocumentType, detectDocumentType } from "@/features/extraction";
import { generateLegalMemo } from "../services/checklist-generator";
// jspdf is intentionally NOT statically imported here (~343KB stat / ~105KB
// gzip). It loads only inside handleExportPdf on Download click, so opening
// the Export tab never pays the PDF parse/compile cost.
import { LawyerQuestionsCard } from "./lawyer-questions-card";
import { useLawyerChecklist } from "../store/lawyer-checklist-store";
// Negotiation workspace is code-split behind the "Draft Negotiation Email"
// toggle — its LLM streaming hook + framer-motion usage stay out of both the
// initial bundle and the memo screen chunk until requested.
const NegotiationEmailWorkspace = dynamic(
  () => import("@/features/negotiation-email").then((mod) => mod.NegotiationEmailWorkspace),
  {
    ssr: false,
    loading: () => (
      <div className="rounded-lg border border-dashed border-border bg-card p-8 text-center text-sm text-muted-foreground">
        Loading negotiation workspace…
      </div>
    ),
  }
);
import { Button } from "@/ui/button";
import { Download, Printer, Copy, Check, CheckCircle2, RefreshCw, Scale, Mail } from "lucide-react";

interface ChecklistMemoScreenProps {
  doc: ParsedDocument;
  clauses: Clause[];
  extractionStatus?: "idle" | "extracting" | "success" | "error";
  onRunExtraction?: () => void;
  bookmarkedQuestions?: string[];
  documentType?: DocumentType;
}

export function ChecklistMemoScreen({
  doc,
  clauses,
  extractionStatus = "idle",
  onRunExtraction,
  bookmarkedQuestions = [],
  documentType,
}: ChecklistMemoScreenProps): JSX.Element {
  const { questions: storeQuestions } = useLawyerChecklist();

  const isExtractionComplete =
    (extractionStatus === "success" || clauses.length > 0) && extractionStatus !== "extracting";

  const allBookmarkedQuestions = useMemo(() => {
    const combined = new Set([...bookmarkedQuestions, ...storeQuestions]);
    return Array.from(combined);
  }, [bookmarkedQuestions, storeQuestions]);

  const docType = documentType || detectDocumentType(doc);

  const memo = useMemo(
    () =>
      isExtractionComplete
        ? generateLegalMemo(doc, clauses, allBookmarkedQuestions, docType)
        : null,
    [doc, clauses, allBookmarkedQuestions, isExtractionComplete, docType]
  );

  const [checkedActions, setCheckedActions] = useState<Record<string, boolean>>({});
  const [copiedMemo, setCopiedMemo] = useState(false);
  const [showNegotiationEmail, setShowNegotiationEmail] = useState(false);

  const toggleAction = (id: string) => {
    setCheckedActions((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const handleExportPdf = () => {
    if (!memo) return;
    // On-demand jspdf chunk: fetched only on explicit Download click.
    void import("../services/pdf-exporter").then(({ exportLegalMemoToPdf }) =>
      exportLegalMemoToPdf(memo)
    );
  };

  const handlePrint = () => {
    if (memo) window.print();
  };

  const handleCopyText = () => {
    if (!memo) return;

    const textLines = [
      `NYAYSETU LEGAL PREPARATION MEMORANDUM`,
      `=====================================`,
      `Document: ${memo.documentFilename}`,
      `Case Reference: ${memo.caseReference}`,
      `Date: ${memo.generatedDate}`,
      `Risk Profile: ${memo.highRiskCount} High-Risk / ${memo.cautionCount} Caution Provisions`,
      ``,
      `1. ACTION CHECKLIST (BEFORE SIGNING):`,
      ...memo.actionItems.map(
        (a, i) => `[${checkedActions[a.id] ? "X" : " "}] ${i + 1}. ${a.text}`
      ),
      ``,
      `2. QUESTIONS FOR YOUR LEGAL ADVISOR:`,
      ...memo.lawyerQuestions.map((q, i) => `Q${i + 1}: ${q.text}`),
      ``,
      `STATUTORY CITATIONS:`,
      ...memo.statutoryCitations.map((s) => `- ${s}`),
      ``,
      `Disclaimer: Generated by NyaySetu for legal-aid and advocate consultation preparation.`,
    ].join("\n");

    void navigator.clipboard.writeText(textLines);
    setCopiedMemo(true);
    setTimeout(() => setCopiedMemo(false), 2000);
  };

  const completedCount = memo ? memo.actionItems.filter((a) => checkedActions[a.id]).length : 0;

  return (
    <div className="mx-auto max-w-4xl space-y-6">
      {/* Top Action Toolbar (Hidden in Print) */}
      <div className="flex flex-col gap-4 rounded-lg border border-[#E0D7C6] bg-[#FBF9F4] p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between print:hidden">
        <div>
          <span className="font-mono text-xs uppercase tracking-wider text-[#684B1E]">
            Feature F6 · Automated Consultation Memo
          </span>
          <h2 className="font-serif text-lg text-[#1B2430]">
            Legal Preparation Memo &amp; Checklist
          </h2>
          <p className="text-xs text-[#525D6B]">
            Export-ready one-pager compiled from session risk data with zero extra input
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            type="button"
            disabled={!isExtractionComplete || !memo}
            onClick={handleExportPdf}
            className="shadow-xs inline-flex items-center gap-1.5 rounded bg-[#1B2430] px-3.5 py-2 font-mono text-xs font-semibold text-[#F7F3EA] transition-colors hover:bg-[#111822] disabled:cursor-not-allowed disabled:opacity-50"
            aria-label="Export official PDF memo"
          >
            <Download className="h-3.5 w-3.5 text-[#684B1E]" />
            Download PDF
          </button>

          <button
            type="button"
            disabled={!isExtractionComplete || !memo}
            onClick={handlePrint}
            className="inline-flex items-center gap-1.5 rounded border border-[#E0D7C6] bg-[#F7F3EA] px-3 py-2 font-mono text-xs text-[#1B2430] transition-colors hover:bg-[#EFE8DC] disabled:cursor-not-allowed disabled:opacity-50"
            aria-label="Print memorandum"
          >
            <Printer className="h-3.5 w-3.5 text-[#525D6B]" />
            Print
          </button>

          <button
            type="button"
            disabled={!isExtractionComplete || !memo}
            onClick={handleCopyText}
            className="inline-flex items-center gap-1.5 rounded border border-[#E0D7C6] bg-[#F7F3EA] px-3 py-2 font-mono text-xs text-[#1B2430] transition-colors hover:bg-[#EFE8DC] disabled:cursor-not-allowed disabled:opacity-50"
            aria-label="Copy memo text"
          >
            {copiedMemo ? (
              <>
                <Check className="h-3.5 w-3.5 text-[#3F6C51]" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5 text-[#525D6B]" />
                Copy Text
              </>
            )}
          </button>

          <button
            type="button"
            disabled={!isExtractionComplete || !memo}
            onClick={() => setShowNegotiationEmail((prev) => !prev)}
            className={`inline-flex items-center gap-1.5 rounded border px-3 py-2 font-mono text-xs transition-colors disabled:cursor-not-allowed disabled:opacity-50 ${
              showNegotiationEmail
                ? "border-[#B08D57] bg-[#FAF3E8] font-bold text-[#684B1E]"
                : "border-[#E0D7C6] bg-[#F7F3EA] text-[#1B2430] hover:bg-[#EFE8DC]"
            }`}
            aria-label="Draft a negotiation email"
            aria-expanded={showNegotiationEmail}
          >
            <Mail className="h-3.5 w-3.5 text-[#684B1E]" />
            Draft Negotiation Email
          </button>
        </div>
      </div>

      {/* Negotiation Email Drafting Workspace (Fourth Export Action) */}
      {showNegotiationEmail && isExtractionComplete && (
        <NegotiationEmailWorkspace
          documentFilename={doc.filename}
          documentType={docType}
          clauses={clauses}
          onClose={() => setShowNegotiationEmail(false)}
        />
      )}

      {/* Gating: If extraction has not finished, display clear inline prompt instead of returning an empty memo */}
      {!isExtractionComplete ? (
        extractionStatus === "extracting" ? (
          <div className="shadow-xs space-y-4 rounded-xl border border-[#E0D7C6] bg-[#FDFBF7] p-12 text-center">
            <RefreshCw className="mx-auto h-8 w-8 animate-spin text-[#684B1E]" />
            <h3 className="font-serif text-base font-semibold text-[#1B2430]">
              Extracting Operative Clauses &amp; Assessing Risks...
            </h3>
            <p className="mx-auto max-w-md text-xs leading-relaxed text-[#525D6B]">
              NyaySetu is actively analyzing clauses from{" "}
              <span className="font-semibold text-primary">{doc.filename}</span>. Your executive
              legal preparation memo and action checklist will generate automatically once
              extraction completes.
            </p>
          </div>
        ) : (
          <div className="space-y-4 rounded-xl border-2 border-[#B08D57]/40 bg-[#FDFBF7] p-10 text-center shadow-sm">
            <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-[#B08D57]/10 text-[#684B1E]">
              <Scale className="h-6 w-6" />
            </div>
            <div className="space-y-1.5">
              <h3 className="font-serif text-base font-semibold text-[#1B2430]">
                Clause Extraction Required for Legal Preparation Memo
              </h3>
              <p className="mx-auto max-w-lg text-xs leading-relaxed text-[#525D6B]">
                The legal preparation memorandum derives risk classifications, advocate consultation
                questions, and pre-signing action items directly from extracted operative clauses.
                Opening this view before extraction would produce a false negative memo with zero
                detected risks. Please extract clauses first.
              </p>
            </div>
            {onRunExtraction && (
              <Button variant="brass" onClick={onRunExtraction}>
                <Scale className="mr-2 h-4 w-4" />
                Extract Clauses &amp; Assess Risks
              </Button>
            )}
          </div>
        )
      ) : memo ? (
        /* Official Letter / Memorandum Paper Sheet */
        <article className="space-y-8 rounded-xl border border-[#E0D7C6] bg-[#FDFBF7] p-8 shadow-md sm:p-12 print:border-none print:p-0 print:shadow-none">
          {/* Letterhead Header */}
          <header className="space-y-4 border-b-2 border-[#1B2430] pb-6">
            <div className="flex items-center justify-between">
              <span className="font-mono text-xs font-semibold uppercase tracking-widest text-[#684B1E]">
                NYAYSETU · CLINICAL PREPARATION MEMO
              </span>
              <span className="font-mono text-xs text-[#525D6B]">REF: {memo.caseReference}</span>
            </div>

            <div>
              <h1 className="font-serif text-2xl font-bold tracking-tight text-[#1B2430] sm:text-3xl">
                Legal Preparation Memorandum
              </h1>
              <p className="mt-1 font-sans text-xs text-[#525D6B]">
                Prepared for citizen advocacy, legal clinic intake, and formal lawyer briefing
              </p>
            </div>

            {/* Metadata Grid */}
            <div className="grid grid-cols-2 gap-4 rounded-lg border border-[#E0D7C6] bg-[#F7F3EA] p-4 text-xs sm:grid-cols-4">
              <div>
                <span className="font-mono text-[10px] uppercase text-[#8A94A1]">Document</span>
                <p className="truncate font-semibold text-[#1B2430]">{memo.documentFilename}</p>
              </div>
              <div>
                <span className="font-mono text-[10px] uppercase text-[#8A94A1]">Date</span>
                <p className="font-semibold text-[#1B2430]">{memo.generatedDate}</p>
              </div>
              <div>
                <span className="font-mono text-[10px] uppercase text-[#8A94A1]">Risk Profile</span>
                <p className="font-semibold text-[#8C2F39]">
                  {memo.highRiskCount} High-Risk / {memo.cautionCount} Caution
                </p>
              </div>
              <div>
                <span className="font-mono text-[10px] uppercase text-[#8A94A1]">Total Scope</span>
                <p className="font-semibold text-[#1B2430]">{memo.totalClauses} Clauses</p>
              </div>
            </div>
          </header>

          {/* Section 1: Executive Action Checklist */}
          <section aria-labelledby="action-checklist-heading" className="space-y-4">
            <div className="flex items-center justify-between border-b border-[#E0D7C6] pb-2">
              <h2
                id="action-checklist-heading"
                className="font-serif text-base font-semibold text-[#1B2430]"
              >
                1. Executive Action Checklist (Before Signing)
              </h2>
              <span className="font-mono text-xs text-[#525D6B]">
                {completedCount} of {memo.actionItems.length} completed
              </span>
            </div>

            <ol className="space-y-2.5">
              {memo.actionItems.map((item, idx) => {
                const isChecked = !!checkedActions[item.id];
                return (
                  <li key={item.id}>
                    <button
                      type="button"
                      onClick={() => toggleAction(item.id)}
                      className={`flex w-full cursor-pointer items-start gap-3 rounded border p-3 text-left transition-colors ${
                        isChecked
                          ? "border-[#3F6C51]/30 bg-[#EAF2EC]/50 text-[#525D6B]"
                          : "border-[#E0D7C6] bg-white text-[#1B2430] hover:bg-[#FDFBF7]"
                      }`}
                    >
                      <span className="mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded border border-[#8A94A1]">
                        {isChecked && <CheckCircle2 className="h-3.5 w-3.5 text-[#3F6C51]" />}
                      </span>
                      <div className="flex-1 text-xs leading-relaxed">
                        <span className="mr-1.5 font-mono font-bold text-[#684B1E]">
                          {idx + 1}.
                        </span>
                        <span className={isChecked ? "line-through" : ""}>{item.text}</span>
                      </div>
                    </button>
                  </li>
                );
              })}
            </ol>
          </section>

          {/* Section 2: Questions for Your Lawyer (Bordered Card) */}
          <LawyerQuestionsCard questions={memo.lawyerQuestions} />

          {/* Section 3: Statutory Benchmarks Cited */}
          {memo.statutoryCitations.length > 0 && (
            <section
              aria-labelledby="statutory-citations-heading"
              className="space-y-2 rounded-lg border border-[#E0D7C6] bg-[#F7F3EA] p-4 text-xs"
            >
              <h3
                id="statutory-citations-heading"
                className="font-serif font-semibold text-[#1B2430]"
              >
                Statutory Provisions &amp; Standards Referenced
              </h3>
              <ul className="list-inside list-disc space-y-1 font-mono text-[11px] text-[#525D6B]">
                {memo.statutoryCitations.map((citation, i) => (
                  <li key={i}>{citation}</li>
                ))}
              </ul>
            </section>
          )}

          {/* Formal Legal Disclaimer Footer */}
          <footer className="space-y-1 border-t border-[#E0D7C6] pt-6 text-[11px] italic leading-relaxed text-[#8A94A1]">
            <p>
              DISCLAIMER: This legal preparation memorandum was generated by NyaySetu based solely
              on the four corners of <strong>{memo.documentFilename}</strong>. It is designed to
              assist citizens and advocates at free legal-aid clinics and does not constitute formal
              legal advice or an attorney-client relationship.
            </p>
          </footer>
        </article>
      ) : null}
    </div>
  );
}
